version: 0.2
phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region eu-west-2)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - docker build -t $AWS_ECR/carparks:latest --build-arg build=$COMMIT_HASH --build-arg version=$IMAGE_TAG --build-arg serviceName=carparks -f Dockerfile .
      - docker tag $AWS_ECR/carparks:latest $AWS_ECR/carparks:$IMAGE_TAG
  post_build:
    commands:
      - docker push $AWS_ECR/carparks:$IMAGE_TAG
      - docker push $AWS_ECR/carparks:latest