version: 0.2
phases:
  build:
    commands:
      - docker build -t $AWS_ECR/carparks:$CODEBUILD_SOURCE_VERSION --build-arg build=$CODEBUILD_SOURCE_VERSION --build-arg version=$CODEBUILD_SOURCE_VERSION --build-arg serviceName=carparks -f Dockerfile .
  post_build:
    commands:
      - docker push $AWS_ECR/carparks:$CODEBUILD_SOURCE_VERSION